name: model_wine_quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3

      - name: cml_run
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
